recipient: oskar.hollinsworth@gmail.com
subject: "Today's Machine Learning Papers from arXiv"
url: "http://export.arxiv.org/api/query?search_query=cat:cs.LG&start=0&max_results=300&sortBy=submittedDate&sortOrder=descending"
scoring:
  bias: -20
  summary_multiplier: 0.2
  words:
    - word: "interpretability"
      value: 100
    - word: "alignment"
      value: 50
    - word: "grokking"
      value: 20
    - word: "attack"
      value: 20
    - word: "gender"
      value: -50
    - word: "physics"
      value: -50
    - word: "hydrologic"
      value: -50
    - word: "hydrology"
      value: -50
    - word: "disease"
      value: -50
    - word: "medical"
      value: -50
    - word: "fluid dynamics"
      value: -50
    - word: "aerodynamic"
      value: -50
    - word: "cloud"
      value: -50
    - word: "quantum"
      value: -50
    - word: "diffusion"
      value: -20
    - word: "algebraic"
      value: -20
    - word: "monte carlo"
      value: -10
    - word: "explainability"
      value: -10
    - word: "explainable"
      value: -10
    - word: "privacy"
      value: -20
    - word: "differential equation"
      value: -50
    - word: "finite group"
      value: -50
    - word: "vulnerab"
      value: 50
    - word: "federated"
      value: -50
    - word: "graph representation"
      value: -20
    - word: "graph neural network"
      value: -50
    - word: "molecul"
      value: -50
    - word: "safe"
      value: 50
    - word: "guarantee"
      value: 30
    - word: "geometr"
      value: -30
    - word: "manufactur"
      value: -30
    - word: "compiler"
      value: -50
    - word: "health"
      value: -50
    - word: "marketing"
      value: -50
    - word: "manifold"
      value: -30
    - word: "martingale"
      value: -30
    - word: "robotic"
      value: -50
    - word: "image"
      value: -30
    - word: "recommend"
      value: -30
    - word: "recommendation"
      value: -50
    - word: "jailbreak"
      value: 30
    - word: "robust"
      value: 50
    - word: "svm"
      value: -50
    - word: "rheolog"
      value: -50
    - word: "muscle"
      value: -50
    - word: "latency"
      value: -30  
    - word: "accelerate"
      value: -10
    - word: "performance"
      value: -10
    - word: "energy"
      value: -20
    - word: "home"
      value: -20
    - word: "precision"
      value: -10
    - word: "ontology"
      value: -10
    - word: "compliance"
      value: -30
    - word: "random forest"
      value: -50
    - word: "regression"
      value: -30
    - word: "arthritis"
      value: -200
    - word: "heart"
      value: -50
    - word: "knee"
      value: -50
    - word: "matrix"
      value: -30
    - word: "matrices"
      value: -30
    - word: "collaborative"
      value: -30
    - word: "traffic"
      value: -50
    - word: "climate"
      value: -50
    - word: "atmospher"
      value: -50
    - word: "social"
      value: -30
    - word: "backdoor"
      value: 20
    - word: "portfolio"
      value: -50
    - word: "compression"
      value: -30
    - word: "streaming"
      value: -30
    - word: "smoothing"
      value: -30
    - word: "translation"
      value: -30
    - word: "autonomous"
      value: -50
    - word: "driving"
      value: -50
    - word: "wave"
      value: -30
    - word: "cox"
      value: -20
    - word: "regularization"
      value: -10
    - word: "sparse"
      value: 20
    - word: "embodied"
      value: -50
    - word: "data augmentation"
      value: -30
    - word: "nearest neighbor"
      value: -30
    - word: "prognosis"
      value: -100
    - word: "vision"
      value: -50
    - word: "speech"
      value: -50
    - word: "cnn"
      value: -50
    - word: "topology"
      value: -50
    - word: "topological"
      value: -50
    - word: "cluster"
      value: -30
    - word: "ethereum"
      value: -50
    - word: "blockchain"
      value: -50
    - word: "crypto"
      value: -50
    - word: "hardness"
      value: -30
    - word: "orbit"
      value: -50
    - word: "polynomial"
      value: -50
    - word: "earth"
      value: -50
    - word: "seismic"
      value: -50
    - word: "audio"
      value: -50
    - word: "music"
      value: -50
    - word: "multimodal"
      value: -30
    - word: "quantization"
      value: -20
    - word: "mixture-of-experts"
      value: -20
    - word: "estimation"
      value: -30
    - word: "sample size"
      value: -30
    - word: "confidence bound"
      value: -20
    - word: "feature selection"
      value: -30
    - word: "mathemat"
      value: -50
    - word: "semantic"
      value: -10
    - word: "weather"
      value: -50
    - word: "animal"
      value: -50
    - word: "signal modulation"
      value: -20
    - word: "ecg"
      value: -50
    - word: "electro"
      value: -50
    - word: "cardio"
      value: -50
    - word: "axiom"
      value: -50
    - word: "statistical model"
      value: -30
    - word: "kolmogorov"
      value: -20
    - word: "gaussian"
      value: -20
    - word: "anomaly"
      value: -40
    - word: "protein"
      value: -50
    - word: "biomarker"
      value: -50
    - word: "mri"
      value: -20
    - word: "alzheimer"
      value: -50
    - word: "java"
      value: -20
    - word: "bayesian optimization"
      value: -20
    - word: "cancer"
      value: -50
    - word: "omics"
      value: -30
    - word: "stock"
      value: -50
    - word: "gnn"
      value: -50
    - word: "unlearning"
      value: 50
    - word: "communication"
      value: -50
    - word: "spanning"
      value: -30
    - word: "tabular"
      value: -50
    - word: "hybrid"
      value: -20
    - word: "school"
      value: -50
    - word: "entropy"
      value: -20
    - word: "clinic"
      value: -50
    - word: "batteries"
      value: -50
    - word: "operational"
      value: -30
    - word: "resource"
      value: -30
    - word: "eco-"
      value: -50
    - word: "treatment"
      value: -30
    - word: "metastasis"
      value: -100
    - word: "multilingual"
      value: -30
    - word: "bandit"
      value: -30
    - word: "mixture"
      value: -10
    - word: "personal"
      value: -30
    - word: "linear programming"
      value: -100
    - word: "adversarial"
      value: 50
    - word: "decision tree"
      value: -30
    - word: "continual learning"
      value: -30
    - word: "pruning"
      value: -30
    - word: "spectral"
      value: -30
    - word: "transport"
      value: -50
    - word: "neurosymbolic"
      value: -30
    - word: "sustainability"
      value: -50
    - word: "convolution"
      value: -30
    - word: "drug"
      value: -50
    - word: "directed graph"
      value: -50
    - word: "minimax"
      value: -20
    - word: "model merging"
      value: -50
    - word: "function approximation"
      value: -50
    - word: "financial"
      value: -50
    - word: "receiver"
      value: -100
    - word: "time series"
      value: -50
    - word: "ml4vis"
      value: -100
    - word: "visualization"
      value: -30
    - word: "gandalf"
      value: 50
    - word: "aviation"
      value: -50
    - word: "faithful"
      value: 50
    - word: "inference-time compute"
      value: 200
    - word: "test-time compute"
      value: 200
    - word: "finetuning api"
      value: 100
    - word: "prompt injection"
      value: 100
    - word: "grpo"
      value: 50
    - word: "gspo"
      value: 50
    - word: "misalignment"
      value: 100
    - word: "reasoning"
      value: 50
    - word: "chain of thought"
      value: 50
    - word: "deception"
      value: 100
    - word: "data filtering"
      value: 100
  authors:
    - author: "Adam Gleave"
      value: 300
    - author: "Neel Nanda"
      value: 200
    - author: "Dan Hendrycks"
      value: 100
    - author: "David Bau"
      value: 20
    - author: "Samuel Marks"
      value: 20
    - author: "Kellin Pelrine"
      value: 50
    - author: "Buck Shlegeris"
      value: 200
    - author: "Dario Amodei"
      value: 100
    - author: "Chris Olah"
      value: 100
    - author: "Jan Leike"
      value: 100
    - author: "Rohin Shah"
      value: 100
    - author: "Doina Precup"
      value: 100
    - author: "OpenAI"
      value: 200
    - author: "Owain Evans"
      value: 100
    - author: "Marius Hobbhahn"
      value: 100
    - author: "Yarin Gal"
      value: 100
    - author: "Robert Kirk"
      value: 100
    - author: "Xander Davies"
      value: 100
    - author: "Lisa Schut"
      value: 50
    - author: "Yoshua Bengio"
      value: 50
    - author: "Nicholas Carlini"
      value: 100
    - author: "Joseph Needham"
      value: 100
    - author: "Nina Panickssery"
      value: 50
    - author: "Erik Jones"
      value: 50
  tags:
    - tag: "cs.CV"
      value: -200
    - tag: "cs.SD"
      value: -200
    - tag: "cs.IV"
      value: -200
